import{a as b,S,i as s}from"./assets/vendor-LvtvrCkc.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const q="53608703-aa0418faf5290c51b47c4c69e",P="https://pixabay.com/api/";async function f(t,o=1){try{return(await b.get(P,{params:{key:q,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o}})).data}catch{throw new Error("Error")}}const m=document.querySelector(".gallery"),y=document.querySelector(".loader"),M=new S(".gallery a");function h(t){const o=t.map(({webformatURL:n,largeImageURL:c,tags:e,likes:r,views:a,comments:v,downloads:E})=>`
    <li class="gallery-item">
      <a href="${c}">
        <img src="${n}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p>Likes: ${r}</p>
        <p>Views: ${a}</p>
        <p>Comments: ${v}</p>
        <p>Downloads: ${E}</p>
      </div>
    </li>
  `).join("");m.insertAdjacentHTML("beforeend",o),M.refresh()}function $(){m.innerHTML=""}function p(){y.classList.remove("hidden")}function g(){y.classList.add("hidden")}const L=document.querySelector(".form"),A=L.querySelector('input[name="search-text"]'),u=document.querySelector(".load-more");let l,i;const w=15;function O(){const t=document.querySelector(".gallery-item");if(!t)return;const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}L.addEventListener("submit",async t=>{t.preventDefault();const o=A.value.trim();if(!o){s.warning({title:"Warning",message:"Please enter a search query!"});return}l=o,i=1,$(),d(),p();try{const n=await f(l,i);if(!n.hits.length){s.info({title:"No results",message:"Sorry, no images found."});return}if(h(n.hits),n.totalHits<=w){d(),s.info({title:"End",message:"We're sorry, but you've reached the end of search results."});return}B()}catch{s.error({title:"Error",message:"Failed to load images"})}finally{g()}});u.addEventListener("click",async()=>{i+=1,await x()});async function x(){p();try{const t=await f(l,i);if(h(t.hits),O(),i*w>=t.totalHits){d(),s.info({title:"End",message:"We're sorry, but you've reached the end of search results."});return}}catch{s.error({title:"Error",message:"Failed to load more images"})}finally{g()}}function B(){u.classList.remove("hidden")}function d(){u.classList.add("hidden")}
//# sourceMappingURL=index.js.map
